services:
  - type: web
    name: vehicle-number-plate-detection
    runtime: python3.11
    region: Oregon
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT

